[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4" 
domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }
serde = { version = "1", features = ["derive"] } 
uuid = "1"